

import React, { useState, useEffect, useRef, useCallback } from 'react';
import { BarChart3, X } from 'lucide-react';

interface PopularityBannerProps {
    totalUsage: number;
    onClose: () => void;
}

const PopularityBanner: React.FC<PopularityBannerProps> = ({ totalUsage, onClose }) => {
    const [isVisible, setIsVisible] = useState(false);
    
    const onCloseRef = useRef(onClose);
    useEffect(() => {
        onCloseRef.current = onClose;
    });

    const handleClose = useCallback(() => {
        setIsVisible(false);
        setTimeout(() => onCloseRef.current(), 500); // 500ms matches CSS transition duration
    }, []);

    useEffect(() => {
        const mountTimer = setTimeout(() => setIsVisible(true), 100);
        const closeTimer = setTimeout(handleClose, 5000); // Auto-close after 5 seconds

        return () => {
            clearTimeout(mountTimer);
            clearTimeout(closeTimer);
        };
    }, [handleClose]);

    if (totalUsage <= 0) {
        return null; // Don't show if there's no usage history
    }

    const message = `Total reports generated by this app till now: ${totalUsage.toLocaleString()}`;

    return (
        <div 
            className={`w-fit mx-auto max-w-full bg-indigo-600/90 backdrop-blur-sm text-white rounded-full shadow-lg flex items-center gap-4 px-5 py-3 transition-all duration-500 ease-out
                ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 -translate-y-4'}`
            }
            role="status"
            aria-live="polite"
        >
            <BarChart3 size={20} className="flex-shrink-0" />
            <span className="font-semibold text-sm whitespace-nowrap">{message}</span>
            <button 
                onClick={handleClose} 
                className="ml-2 p-1 rounded-full hover:bg-white/20 transition-colors flex-shrink-0"
                aria-label="Dismiss message"
            >
                <X size={18} />
            </button>
        </div>
    );
};

export default PopularityBanner;